### ISSUE TITLE
No auto icon config when using `Create map note`

### ISSUE THREAD

**Issue by sylvercode** [tcflanag/journal_icon_numbers#2]
When creating map note pin from the `Create map note` tool, the Note Config of the module is hidden.

![image](https://github.com/user-attachments/assets/bfc00334-51e6-4ca5-ad8a-9141a8c34229)

I think is because of this line:
https://github.com/tcflanag/journal_icon_numbers/blob/4dbe1367487c8f63c30e90380eaa6ab6cdafb340/src/index.js#L107

I try this code: `if (firstTime && flags.iconText === undefined)` and it seems to work but I am not sure what is the use case that is describe bellow in the comment where we dont want the note config.

Any idea?

**Comment by tcflanag** [comment]
Huh, I'm not sure I knew you could create pins that way.  When I was using foundry, I only ever created them by dragging from the Journal.
